source 'https://rubygems.org'

gem 'rails', '3.2.13.rc2'

# Database
gem 'pg'
gem 'foreigner'

# Server
gem 'thin'

# Improvements
gem 'strong_parameters'
gem 'inherited_resources'
#gem 'simple_form'
#gem 'jbuilder'

# I18n
gem 'rails-i18n'
#gem 'devise-i18n'

# Authentication
#gem 'devise'
#gem 'omniauth'
#gem 'omniauth-facebook'
#gem 'omniauth-twitter'

# Frontend stuff
gem 'jquery-rails'
gem 'slim-rails'
gem 'initjs'
gem 'flutie'
#gem 'rack-google-analytics'

group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'compass-rails'
  gem 'uglifier'
  #gem 'turbolinks'
  #gem 'bootstrap-sass'
  #gem 'zurb-foundation'
  #gem 'angular-rails'
end

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
#group :production do
  #gem 'execjs'
  #gem 'therubyracer', platform: :ruby
#end

group :development, :test do
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'machinist'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'pry'
  gem 'awesome_print'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'quiet_assets'
end
